### ISSUE TITLE
Inline styling on wrapper div

### ISSUE THREAD

**Issue by Maismaus** [ivosturm/GoogleMapsCustomMarkerReact#6]
There are styling rules on the wrapper div:
height: 90vh;
width: 0%;

This messes up the page on my end. Why is this in place? It seems to work fine without those rules.

https://github.com/ivosturm/GoogleMapsCustomMarkerReact/blob/5208a2ee5872ce098affbc16f40d91c72005864b/src/components/GoogleMapsContainer.tsx#L306

**Comment by ivosturm** [comment]
Hi both, I added two settings Height and Width in which you can set the dimensions. Setting either to 10.000 will make it responsive and try to fill the full width / height respectively. See description in the widget settings as well.
