### ISSUE TITLE
Deprecation issue for latAttr and lngAttr retrieval

### ISSUE THREAD

**Issue by Maismaus** [ivosturm/GoogleMapsCustomMarkerReact#7]
Probably should replace the function calls on line 205 and 206

[Client] DEPRECATED: direct usage of List attribute "288.Module.Page.googleMapsCustomMarker1//latAttr" as a function, use .get() instead -- will be removed in version: 10.0

https://github.com/ivosturm/GoogleMapsCustomMarkerReact/blob/5208a2ee5872ce098affbc16f40d91c72005864b/src/components/GoogleMapsContainer.tsx#L205

**Comment by kleineroscar** [comment]
Hi @Maismaus just letting you know that I created a fork (and pull request) with a version that works in mx10. I also added a fix for the styling issue.
[Link to build](https://github.com/kleineroscar/GoogleMapsCustomMarkerReact/actions/runs/5573150033)

**Comment by ivosturm** [comment]
Hi both, I added a fix for this in the newest version, 1.3.0, now available in the Mendix Marketplace. Let me know if it doesn't work!
